import assert from "node:assert/strict";import test from "node:test";
import { FakeProviderAdapter, NormalizedProviderError } from "../src/providers/adapter.js";import { ProviderRegistry } from "../src/providers/registry.js";import { estimateCost, route } from "../src/providers/router.js";import type { Capability, Model, RouteRequest } from "../src/providers/types.js";
const at=new Date("2026-08-08T00:00:00Z");
function model(id:string,cost:number,quality:number,latency:number,caps:Capability[]=["text","tools"]):Model{return{id,providerId:`p-${id}`,accountId:`a-${id}`,name:id,lifecycle:"active",capabilities:new Set(caps),contextLimit:100_000,outputLimit:10_000,health:"healthy",latencyMs:latency,quality,reliability:.99,prices:[{effectiveFrom:new Date("2026-01-01Z"),inputUsdMicrosPerMillion:cost,outputUsdMicrosPerMillion:cost}]};}
function registry(...models:Model[]):ProviderRegistry{const r=new ProviderRegistry();for(const m of models){r.addProvider({id:m.providerId,name:m.providerId,lifecycle:"active"});r.addAccount({id:m.accountId,providerId:m.providerId,secretRef:`secret://${m.accountId}`,region:"global",lifecycle:"active"});r.addModel(m);}return r;}
const request=(mode:RouteRequest["mode"]):RouteRequest=>({mode,required:new Set(["text","tools"]),inputTokens:1000,outputTokens:1000,maxCostUsdMicros:1000,contextTokens:5000,maxFallbacks:2});
test("pricing selects the effective version and rejects gaps",()=>{const m=model("m",10,.5,10);m.prices=[{effectiveFrom:new Date("2025-01-01Z"),effectiveTo:new Date("2026-01-01Z"),inputUsdMicrosPerMillion:1,outputUsdMicrosPerMillion:1},{effectiveFrom:new Date("2026-01-01Z"),inputUsdMicrosPerMillion:10,outputUsdMicrosPerMillion:20}];assert.equal(estimateCost(m,1_000_000,1_000_000,at),30);assert.equal(estimateCost(m,1,1,new Date("2024-01-01Z")),undefined);});
test("all routing modes are deterministic and explain fallback",()=>{const cheap=model("cheap",100,.5,900),fast=model("fast",10_000,.7,10),best=model("best",20_000,.99,500);const r=registry(cheap,fast,best);assert.equal(route(r,request("lowest_cost"),at).outcome,"selected");assert.equal((route(r,request("lowest_cost"),at) as any).selected.model.id,"cheap");assert.equal((route(r,request("fastest"),at) as any).selected.model.id,"fast");assert.equal((route(r,request("highest_quality"),at) as any).selected.model.id,"best");assert.equal((route(r,request("balanced"),at) as any).fallbacks.length,2);assert.equal((route(r,{...request("manual"),manualModelId:"fast"},at) as any).selected.model.id,"fast");assert.equal((route(r,{...request("policy_locked"),policyModelIds:new Set(["cheap"])},at) as any).selected.model.id,"cheap");});
test("eligibility fails closed with explicit reasons",()=>{const m=model("bad",10,.8,10,["text"]);m.health="down";const result=route(registry(m),request("balanced"),at);assert.equal(result.outcome,"blocked");assert.deepEqual(result.rejected[0]?.reasons,["model_unhealthy","missing_tools"]);const costly=model("costly",1_000_000,.9,10);assert.equal(route(registry(costly),{...request("balanced"),maxCostUsdMicros:1},at).outcome,"blocked");});
test("empirical secure evaluation overrides provider claim",()=>{const claimed=model("claimed",10,.99,10),proven=model("proven",10,.4,10);const r=registry(claimed,proven);r.addEvaluation({id:"e",modelId:"proven",suite:"golden",quality:1,successRate:1,securityPass:true,occurredAt:at,reviewerAgentId:"reviewer"});assert.equal((route(r,request("highest_quality"),at) as any).selected.model.id,"proven");});
test("usage requires complete attribution and secret references only",()=>{const r=registry(model("m",10,.5,10));assert.throws(()=>r.addAccount({id:"raw",providerId:"p-m",secretRef:"plaintext",region:"x",lifecycle:"active"}),/secret reference/);assert.throws(()=>r.addUsage({id:"u",providerId:"p-m",accountId:"a-m",modelId:"m",agentId:"",projectId:"p",contractId:"c",taskId:"t",attemptId:"a",inputTokens:1,outputTokens:1,costUsdMicros:1,occurredAt:at}),/incomplete/);});
test("fake adapter is provider-neutral and normalizes cancellation",async()=>{const adapter=new FakeProviderAdapter("new-provider",["x"]);assert.deepEqual(await adapter.listModels(),["x"]);const controller=new AbortController();controller.abort();await assert.rejects(adapter.complete({model:"x",messages:[],maxOutputTokens:1,signal:controller.signal}),(e:unknown)=>e instanceof NormalizedProviderError&&e.code==="cancelled");});

test("provider kill switch and missing policy allowlist fail closed",()=>{const m=model("m",10,.9,10);const r=new ProviderRegistry();r.addProvider({id:m.providerId,name:"disabled",lifecycle:"disabled"});r.addAccount({id:m.accountId,providerId:m.providerId,secretRef:"secret://a",region:"global",lifecycle:"active"});r.addModel(m);const killed=route(r,request("balanced"),at);assert.equal(killed.outcome,"blocked");assert.ok(killed.rejected[0]?.reasons.includes("provider_not_active"));assert.equal(route(registry(model("active",10,.9,10)),request("policy_locked"),at).outcome,"blocked");});

test("failed security evaluation makes a model ineligible",()=>{const r=registry(model("unsafe",10,.99,10));r.addEvaluation({id:"failed",modelId:"unsafe",suite:"security",quality:1,successRate:1,securityPass:false,occurredAt:at,reviewerAgentId:"independent"});const result=route(r,request("highest_quality"),at);assert.equal(result.outcome,"blocked");assert.ok(result.rejected[0]?.reasons.includes("security_evaluation_failed"));});

test("usage rejects unknown registry references",()=>{const r=registry(model("m",10,.5,10));assert.throws(()=>r.addUsage({id:"u",providerId:"unknown",accountId:"a-m",modelId:"m",agentId:"agent",projectId:"p",contractId:"c",taskId:"t",attemptId:"a",inputTokens:1,outputTokens:1,costUsdMicros:1,occurredAt:at}),/unknown or mismatched/);});

test("registry rejects overlapping price periods",()=>{const m=model("m",10,.5,10);m.prices=[{effectiveFrom:new Date("2026-01-01Z"),inputUsdMicrosPerMillion:1,outputUsdMicrosPerMillion:1},{effectiveFrom:new Date("2026-02-01Z"),inputUsdMicrosPerMillion:2,outputUsdMicrosPerMillion:2}];assert.throws(()=>registry(m),/overlap/);});
