import type { Candidate, Model, PriceVersion, RouteBlocked, RouteDecision, RouteRequest } from "./types.js";
import type { ProviderRegistry } from "./registry.js";

function priceAt(prices:ReadonlyArray<PriceVersion>,at:Date):PriceVersion|undefined{return prices.filter(p=>p.effectiveFrom<=at&&(p.effectiveTo==null||at<p.effectiveTo)).sort((a,b)=>b.effectiveFrom.getTime()-a.effectiveFrom.getTime())[0];}
export function estimateCost(model:Model,input:number,output:number,at:Date):number|undefined{const p=priceAt(model.prices,at);return p===undefined?undefined:Math.ceil((input*p.inputUsdMicrosPerMillion+output*p.outputUsdMicrosPerMillion)/1_000_000);}
export function route(registry:ProviderRegistry,request:RouteRequest,at=new Date()):RouteDecision|RouteBlocked{
 const rejected:{modelId:string;reasons:string[]}[]=[];const eligible:Candidate[]=[];let anyOverBudget=false;
 for(const model of [...registry.listModels()].sort((a,b)=>a.id.localeCompare(b.id))){const reasons:string[]=[];const account=registry.account(model.accountId);
  if(registry.provider(model.providerId)?.lifecycle!=="active")reasons.push("provider_not_active");if(model.lifecycle!=="active")reasons.push("model_not_active");if(account?.lifecycle!=="active")reasons.push("account_not_active");if(model.health!=="healthy")reasons.push("model_unhealthy");if(registry.hasFailedSecurityEvaluation(model.id))reasons.push("security_evaluation_failed");if(request.contextTokens>model.contextLimit||request.outputTokens>model.outputLimit)reasons.push("token_limit");for(const c of request.required)if(!model.capabilities.has(c))reasons.push(`missing_${c}`);if(request.allowedRegions!==undefined&&!request.allowedRegions.has(account?.region??""))reasons.push("region_denied");if(request.policyModelIds!==undefined&&!request.policyModelIds.has(model.id))reasons.push("policy_denied");
  const cost=estimateCost(model,request.inputTokens,request.outputTokens,at);if(cost===undefined)reasons.push("pricing_gap");else if(cost>request.maxCostUsdMicros){reasons.push("budget_exceeded");anyOverBudget=true;}
  if(reasons.length>0)rejected.push({modelId:model.id,reasons});else{const quality=registry.evaluationScore(model.id)??model.quality;const score=.45*quality+.25*model.reliability+.2*(1-Math.min(model.latencyMs/30_000,1))+.1*(1-Math.min((cost??0)/Math.max(request.maxCostUsdMicros,1),1));eligible.push({model,estimatedCostUsdMicros:cost!,score});}}
 if(request.mode==="manual"&&request.manualModelId===undefined)return {outcome:"blocked",reason:"manual_model_unavailable",rejected};if(request.mode==="policy_locked"&&request.policyModelIds===undefined)return {outcome:"blocked",reason:"policy_model_unavailable",rejected};
 let candidates=request.mode==="manual"?eligible.filter(c=>c.model.id===request.manualModelId):eligible;
 if(candidates.length===0)return {outcome:"blocked",reason:request.mode==="manual"?"manual_model_unavailable":anyOverBudget?"budget_exceeded":"no_eligible_model",rejected};
 const compare=request.mode==="lowest_cost"?(a:Candidate,b:Candidate)=>a.estimatedCostUsdMicros-b.estimatedCostUsdMicros||a.model.id.localeCompare(b.model.id):request.mode==="fastest"?(a:Candidate,b:Candidate)=>a.model.latencyMs-b.model.latencyMs||a.model.id.localeCompare(b.model.id):request.mode==="highest_quality"?(a:Candidate,b:Candidate)=>(registry.evaluationScore(b.model.id)??b.model.quality)-(registry.evaluationScore(a.model.id)??a.model.quality)||a.model.id.localeCompare(b.model.id):(a:Candidate,b:Candidate)=>b.score-a.score||a.model.id.localeCompare(b.model.id);
 candidates=[...candidates].sort(compare);return {outcome:"selected",selected:candidates[0]!,fallbacks:candidates.slice(1,1+Math.max(0,request.maxFallbacks)),rejected};
}
